language: python
python:
  - "2.7"
  - "3.5"
install: "pip install -r requirements/development.txt"
script: flake8 src
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/f14e347c422671c7ee5d"
    on_success: change
    on_failure: always
    on_start: never
